// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD83cLIicdp8dgRn5GB1etsNEoK16a_ERw',
    appId: '1:927944866422:web:91e2ffc26552892b2ebd57',
    messagingSenderId: '927944866422',
    projectId: 'flutter-ecommerce-crud-88d70',
    authDomain: 'flutter-ecommerce-crud-88d70.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-crud-88d70.firebasestorage.app',
    measurementId: 'G-65CPDVV71F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc2Kb6Iwbqws59BapvHyVAXVdkMHxfpbQ',
    appId: '1:927944866422:android:88a70696b2aa00d42ebd57',
    messagingSenderId: '927944866422',
    projectId: 'flutter-ecommerce-crud-88d70',
    storageBucket: 'flutter-ecommerce-crud-88d70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4UlscUGWqv_ZhsHioaOF7OJ43KBK8_E0',
    appId: '1:927944866422:ios:c910dff18faac8a92ebd57',
    messagingSenderId: '927944866422',
    projectId: 'flutter-ecommerce-crud-88d70',
    storageBucket: 'flutter-ecommerce-crud-88d70.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4UlscUGWqv_ZhsHioaOF7OJ43KBK8_E0',
    appId: '1:927944866422:ios:c910dff18faac8a92ebd57',
    messagingSenderId: '927944866422',
    projectId: 'flutter-ecommerce-crud-88d70',
    storageBucket: 'flutter-ecommerce-crud-88d70.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD83cLIicdp8dgRn5GB1etsNEoK16a_ERw',
    appId: '1:927944866422:web:e37cc0df6890df9a2ebd57',
    messagingSenderId: '927944866422',
    projectId: 'flutter-ecommerce-crud-88d70',
    authDomain: 'flutter-ecommerce-crud-88d70.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-crud-88d70.firebasestorage.app',
    measurementId: 'G-QXX80R9LFZ',
  );
}
